# Site settings
title: 荔枝味儿的博客
email: 1508490934@qq.com
description: > # this means to ignore newlines until "baseurl:"
  Litchiware's blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://litchiware.github.io" # the base hostname & protocol for your site
twitter_username: Litchiware
github_username:  Litchiware

# Build settings
markdown: kramdown
highlighter: pygments
